// src/infrastructure/repositories/SupabaseAuthRepository.ts
import { supabase } from "@/infrastructure/services/SupabaseClient";
import { AuthRepository } from "@/infrastructure/repositories/AuthRepository";
import { Usuario } from "@/domain/entities/Usuario";
import { Rol } from "@/domain/enums/Rol";
import { InfoUsuario } from "@/domain/entities/InfoUsuario";
import { requestCache } from "@/infrastructure/services/RequestCache";
import { trackAuthCall } from "@/utils/authCallTracker";
import { rateLimitHandler } from "@/infrastructure/services/RateLimitHandler";

// Tipo que representa la estructura exacta de la tabla usuario en Supabase
interface UsuarioSupabase {
    id: number; // bigint generated by default as identity
    created_at: string; // timestamp with time zone
    nombre: string | null;
    idea: string | null;
    avatar: string | null;
    user_auth: string | null; // uuid
    marco: string | null;
    barra_salud: number | null; // numeric
    role: string; // text not null default 'empleado'
    id_usuario: string; // uuid not null
    correo: string | null;
    admin: boolean; // boolean not null default false
    solicitud_nivel: string | null; // uuid
    nivel: number | null; // smallint default 0
    bio: string | null;
    username: string; // text not null
    fecha_nacimiento: string | null; // date
    ubicacion: string | null;
    enlace_github: string | null;
    enlace_web: string | null;
    enlace_linkedin: string | null;
    id_organizacion: string | null; // uuid
}

export class SupabaseAuthRepository implements AuthRepository {
    async login(email: string, password: string): Promise<Usuario | null> {
        try {
            // console.log('🔐 Intentando login con Supabase...');
            const { data, error } = await supabase.auth.signInWithPassword({ 
                email, 
                password 
            });
            
            if (error) {
                // Verificar si es un error 429
                if (rateLimitHandler.isRateLimitError(error)) {
                    rateLimitHandler.handleRateLimitError();
                    console.error('❌ Error 429 (Rate Limit) en login. Cooldown activado.');
                } else {
                    console.error('❌ Error en login:', error);
                }
                return null;
            }
            
            if (!data.user || !data.session) {
                console.error('❌ No se recibió usuario o sesión');
                return null;
            }

            // Limpiar cooldown después de login exitoso
            rateLimitHandler.clearCooldown();
            console.log('✅ Login exitoso, cooldown limpiado');

            // console.log('✅ Login exitoso, sesión creada');
            // console.log('📝 Sesión expira en:', new Date(data.session.expires_at * 1000));

            // Obtener datos adicionales de la tabla usuario
            const userData = await this.getUserData(data.user.id);
            const domainUser = await this.mapToDomainUser(data.user, userData);
            
            // console.log('✅ Usuario del dominio creado exitosamente');
            return domainUser;
        } catch (error) {
            // Verificar si es un error 429
            if (rateLimitHandler.isRateLimitError(error)) {
                rateLimitHandler.handleRateLimitError();
                console.error('❌ Error 429 (Rate Limit) crítico en login. Cooldown activado.');
            } else {
                console.error('❌ Error crítico en login:', error);
            }
            return null;
        }
    }

    async register(email: string, password: string): Promise<Usuario | null> {
        const { data, error } = await supabase.auth.signUp({ email, password });
        if (error || !data.user) return null;

        // Obtener datos adicionales de la tabla usuario
        const userData = await this.getUserData(data.user.id);
        return await this.mapToDomainUser(data.user, userData);
    }

    async logout(): Promise<void> {
        await supabase.auth.signOut();
    }

    // Obtener datos adicionales del usuario desde la tabla usuario
    private async getUserData(userAuthId: string): Promise<UsuarioSupabase | null> {
        // console.log('Buscando usuario con id_usuario:', userAuthId);

        const { data, error } = await supabase
            .from('usuario')
            .select('*')
            .eq('id_usuario', userAuthId)
            .single();

        if (error) {
            console.error('Error fetching user data:', error);
            console.error('Error details:', error);
            return null;
        }

        // console.log('Datos del usuario encontrados:', data);
        return data as UsuarioSupabase;
    }

    // Versión con cache para getUserData
    private async getUserDataCached(userAuthId: string): Promise<UsuarioSupabase | null> {
        return await requestCache.execute(
            `user-data-${userAuthId}`,
            () => this.getUserData(userAuthId),
            5 * 60 * 1000 // Cache por 5 minutos
        );
    }

    // Obtener nombre de la organización por ID
    private async getOrganizacionNombre(organizacionId: string): Promise<string | null> {
        // console.log('🔍 Buscando organización con id:', organizacionId);

        const { data, error } = await supabase
            .from('organizacion')
            .select('nombre')
            .eq('id', organizacionId)
            .single();

        if (error) {
            console.error('❌ Error fetching organizacion:', error);
            console.error('Error details:', error.message, error.code, error.details);
            return null;
        }

        // console.log('✅ Organización encontrada:', data);
        return data?.nombre || null;
    }

    async getCurrentUser(): Promise<Usuario | null> {
        try {
            trackAuthCall('SupabaseAuthRepository.getCurrentUser', 'getSession');
            
            // Verificar que estamos en el cliente
            if (typeof window === 'undefined') {
                // console.log('⚠️ getCurrentUser llamado en el servidor, retornando null');
                return null;
            }

            // Verificar si estamos en cooldown por rate limiting
            if (rateLimitHandler.isRateLimited()) {
                const remaining = Math.ceil(rateLimitHandler.getRemainingCooldown() / 1000);
                console.warn(`⚠️ [getCurrentUser] En cooldown por rate limiting. Esperando ${remaining} segundos...`);
                
                // Intentar obtener del cache aunque esté expirado
                const cachedUser = requestCache.get<Usuario>('current-user');
                if (cachedUser) {
                    console.log('🎯 Usando usuario desde cache (cooldown activo)');
                    return cachedUser;
                }
                
                return null;
            }

            // Usar cache para evitar peticiones duplicadas
            return await requestCache.execute(
                'current-user',
                async () => {
                    // console.log('🔍 Obteniendo usuario actual (sin cache)...');

                    // Primero verificar la sesión
                    const { data: sessionData, error: sessionError } = await supabase.auth.getSession();
                    
                    if (sessionError) {
                        // Verificar si es un error 429
                        if (rateLimitHandler.isRateLimitError(sessionError)) {
                            rateLimitHandler.handleRateLimitError();
                            console.error('❌ Error 429 (Rate Limit) obteniendo sesión. Cooldown activado.');
                            
                            // Intentar obtener del cache aunque esté expirado
                            const cachedUser = requestCache.get<Usuario>('current-user');
                            if (cachedUser) {
                                console.log('🎯 Usando usuario desde cache después de error 429');
                                return cachedUser;
                            }
                        } else {
                            console.error('❌ Error obteniendo sesión:', sessionError);
                        }
                        return null;
                    }

                    if (!sessionData.session) {
                        // console.log('ℹ️ No hay sesión activa');
                        return null;
                    }

                    // console.log('✅ Sesión encontrada, obteniendo datos del usuario...');

                    // Usar los datos de la sesión directamente
                    const user = sessionData.session.user;
                    if (!user) {
                        console.error('❌ No hay usuario en la sesión');
                        return null;
                    }

                    // Obtener datos adicionales de la tabla usuario (también con cache)
                    const userData = await this.getUserDataCached(user.id);
                    return await this.mapToDomainUser(user, userData);
                },
                2 * 60 * 1000 // Cache por 2 minutos
            );
        } catch (error) {
            // Verificar si es un error 429
            if (rateLimitHandler.isRateLimitError(error)) {
                rateLimitHandler.handleRateLimitError();
                console.error('❌ Error 429 (Rate Limit) en getCurrentUser. Cooldown activado.');
                
                // Intentar obtener del cache aunque esté expirado
                const cachedUser = requestCache.get<Usuario>('current-user');
                if (cachedUser) {
                    console.log('🎯 Usando usuario desde cache después de error 429 crítico');
                    return cachedUser;
                }
            } else {
                console.error('❌ Error en getCurrentUser:', error);
            }
            return null;
        }
    }

    async isAuthenticated(): Promise<boolean> {
        try {
            // Verificar que estamos en el cliente
            if (typeof window === 'undefined') {
                return false;
            }

            // Verificar si estamos en cooldown por rate limiting
            if (rateLimitHandler.isRateLimited()) {
                // Si hay cache de usuario, asumir que está autenticado
                const cachedUser = requestCache.get<Usuario>('current-user');
                return !!cachedUser;
            }

            // Solo verificar la sesión, no llamar getUser()
            const { data: sessionData, error: sessionError } = await supabase.auth.getSession();
            
            // Verificar si es un error 429
            if (sessionError && rateLimitHandler.isRateLimitError(sessionError)) {
                rateLimitHandler.handleRateLimitError();
                // Si hay cache de usuario, asumir que está autenticado
                const cachedUser = requestCache.get<Usuario>('current-user');
                return !!cachedUser;
            }
            
            if (sessionError || !sessionData.session) {
                return false;
            }

            // Verificar que la sesión tiene un usuario válido
            return !!sessionData.session.user;
        } catch (error) {
            // Verificar si es un error 429
            if (rateLimitHandler.isRateLimitError(error)) {
                rateLimitHandler.handleRateLimitError();
                // Si hay cache de usuario, asumir que está autenticado
                const cachedUser = requestCache.get<Usuario>('current-user');
                return !!cachedUser;
            } else {
                console.error('❌ Error en isAuthenticated:', error);
            }
            return false;
        }
    }

    // 🔑 Mapear el user de supabase al dominio Usuario
    private async mapToDomainUser(supabaseUser: any, userData: UsuarioSupabase | null = null): Promise<Usuario> {
        // console.log('Mapeando usuario:', { supabaseUser, userData });

        // Obtener nombre de la organización si existe
        let nombreOrganizacion: string | undefined = undefined;
        // console.log('🏢 id_organizacion del usuario:', userData?.id_organizacion);
        if (userData?.id_organizacion) {
            // console.log('🔍 Buscando organización con ID:', userData.id_organizacion);
            const orgNombre = await this.getOrganizacionNombre(userData.id_organizacion);
            // console.log('🏢 Nombre de organización obtenido:', orgNombre);
            if (orgNombre) {
                nombreOrganizacion = orgNombre;
            }
        } else {
            // console.log('⚠️ Usuario no tiene id_organizacion asignado');
        }

        const profile: InfoUsuario = {
            nombre: userData?.nombre || supabaseUser.user_metadata?.nombre || "",
            apellido: undefined, // No está en la BD según el schema
            avatar: userData?.avatar || supabaseUser.user_metadata?.avatar_url || undefined,
            nivel: userData?.nivel || 0,
            fecha_nacimiento: userData?.fecha_nacimiento ? new Date(userData.fecha_nacimiento) : undefined,
            ubicacion: userData?.ubicacion || undefined,
            enlace_github: userData?.enlace_github || undefined,
            enlace_web: userData?.enlace_web || undefined,
            enlace_linkedin: userData?.enlace_linkedin || undefined,
            idea: userData?.idea || undefined,
            marco: userData?.marco || undefined, // Mantener marco como está en la BD
            bio: userData?.bio || undefined,
            username: userData?.username || supabaseUser.email?.split('@')[0] || "",
            correo: userData?.correo || supabaseUser.email,
            nombreOrganizacion: nombreOrganizacion // Campo separado para el nombre de la organización
        };

        // Mapear el rol desde la base de datos
        let role = Rol.MIEMBRO; // por defecto
        if (userData?.role === 'admin') {
            role = Rol.ADMIN;
        }

        const usuario = new Usuario(
            userData?.id_usuario || supabaseUser.id, // UUID del campo id_usuario
            supabaseUser.email,
            role,
            profile,
            Number(userData?.barra_salud) || 100, // Convertir numeric a number
            userData?.user_auth || supabaseUser.id, // UUID del campo user_auth
            userData?.admin || false,
            userData?.id_organizacion || undefined,
            [], // permisos - puedes cargarlos desde otra tabla si es necesario
            new Date(), // ultimaActividad
            "", // ultimaCaptura
            userData?.solicitud_nivel || undefined
        );

        // console.log('Usuario mapeado con organización:', usuario);
        return usuario;
    }
}
