// src/infrastructure/repositories/SupabaseAuthRepository.ts
import { supabase } from "@/infrastructure/services/SupabaseClient";
import { AuthRepository } from "@/infrastructure/repositories/AuthRepository";
import { Usuario } from "@/domain/entities/Usuario";
import { Rol } from "@/domain/enums/Rol";
import { InfoUsuario } from "@/domain/entities/InfoUsuario";

// Tipo que representa la estructura exacta de la tabla usuario en Supabase
interface UsuarioSupabase {
    id: number; // bigint generated by default as identity
    created_at: string; // timestamp with time zone
    nombre: string | null;
    idea: string | null;
    avatar: string | null;
    user_auth: string | null; // uuid
    marco: string | null;
    barra_salud: number | null; // numeric
    role: string; // text not null default 'empleado'
    id_usuario: string; // uuid not null
    correo: string | null;
    admin: boolean; // boolean not null default false
    solicitud_nivel: string | null; // uuid
    nivel: number | null; // smallint default 0
    bio: string | null;
    username: string; // text not null
    fecha_nacimiento: string | null; // date
    ubicacion: string | null;
    enlace_github: string | null;
    enlace_web: string | null;
    enlace_linkedin: string | null;
    id_organizacion: string | null; // uuid
}

export class SupabaseAuthRepository implements AuthRepository {
    async login(email: string, password: string): Promise<Usuario | null> {
        const { data, error } = await supabase.auth.signInWithPassword({ email, password });
        if (error || !data.user) return null;

        // Obtener datos adicionales de la tabla usuario
        const userData = await this.getUserData(data.user.id);
        return await this.mapToDomainUser(data.user, userData);
    }

    async register(email: string, password: string): Promise<Usuario | null> {
        const { data, error } = await supabase.auth.signUp({ email, password });
        if (error || !data.user) return null;

        // Obtener datos adicionales de la tabla usuario
        const userData = await this.getUserData(data.user.id);
        return await this.mapToDomainUser(data.user, userData);
    }

    async logout(): Promise<void> {
        await supabase.auth.signOut();
    }

    // Obtener datos adicionales del usuario desde la tabla usuario
    private async getUserData(userAuthId: string): Promise<UsuarioSupabase | null> {
        console.log('Buscando usuario con id_usuario:', userAuthId);

        const { data, error } = await supabase
            .from('usuario')
            .select('*')
            .eq('id_usuario', userAuthId)
            .single();

        if (error) {
            console.error('Error fetching user data:', error);
            console.error('Error details:', error);
            return null;
        }

        console.log('Datos del usuario encontrados:', data);
        return data as UsuarioSupabase;
    }

    // Obtener nombre de la organización por ID
    private async getOrganizacionNombre(organizacionId: string): Promise<string | null> {
        console.log('Buscando organización con id:', organizacionId);

        const { data, error } = await supabase
            .from('organizacion')
            .select('nombre')
            .eq('id', organizacionId)
            .single();

        if (error) {
            console.error('Error fetching organizacion:', error);
            return null;
        }

        console.log('Organización encontrada:', data);
        return data?.nombre || null;
    }

    async getCurrentUser(): Promise<Usuario | null> {
        const { data, error } = await supabase.auth.getUser();
        if (error || !data.user) return null;

        // Obtener datos adicionales de la tabla usuario
        const userData = await this.getUserData(data.user.id);
        return await this.mapToDomainUser(data.user, userData);
    }

    // 🔑 Mapear el user de supabase al dominio Usuario
    private async mapToDomainUser(supabaseUser: any, userData: UsuarioSupabase | null = null): Promise<Usuario> {
        console.log('Mapeando usuario:', { supabaseUser, userData });

        // Obtener nombre de la organización si existe
        let nombreOrganizacion: string | undefined = undefined;
        if (userData?.id_organizacion) {
            const orgNombre = await this.getOrganizacionNombre(userData.id_organizacion);
            if (orgNombre) {
                nombreOrganizacion = orgNombre;
            }
        }

        const profile: InfoUsuario = {
            nombre: userData?.nombre || supabaseUser.user_metadata?.nombre || "",
            apellido: undefined, // No está en la BD según el schema
            avatar: userData?.avatar || supabaseUser.user_metadata?.avatar_url || undefined,
            nivel: userData?.nivel || 0,
            fecha_nacimiento: userData?.fecha_nacimiento ? new Date(userData.fecha_nacimiento) : undefined,
            ubicacion: userData?.ubicacion || undefined,
            enlace_github: userData?.enlace_github || undefined,
            enlace_web: userData?.enlace_web || undefined,
            enlace_linkedin: userData?.enlace_linkedin || undefined,
            idea: userData?.idea || undefined,
            marco: userData?.marco || undefined, // Mantener marco como está en la BD
            bio: userData?.bio || undefined,
            username: userData?.username || supabaseUser.email?.split('@')[0] || "",
            correo: userData?.correo || supabaseUser.email,
            nombreOrganizacion: nombreOrganizacion // Campo separado para el nombre de la organización
        };

        // Mapear el rol desde la base de datos
        let role = Rol.MIEMBRO; // por defecto
        if (userData?.role === 'admin') {
            role = Rol.ADMIN;
        }

        const usuario = new Usuario(
            userData?.id_usuario || supabaseUser.id, // UUID del campo id_usuario
            supabaseUser.email,
            role,
            profile,
            Number(userData?.barra_salud) || 100, // Convertir numeric a number
            userData?.user_auth || supabaseUser.id, // UUID del campo user_auth
            userData?.admin || false,
            userData?.id_organizacion || undefined,
            [], // permisos - puedes cargarlos desde otra tabla si es necesario
            new Date(), // ultimaActividad
            "", // ultimaCaptura
            userData?.solicitud_nivel || undefined
        );

        console.log('Usuario mapeado con organización:', usuario);
        return usuario;
    }
}
